plugins:
  editorconfig:
    enabled: true
    config:
      editorconfig: .editorconfig

  phpcodesniffer:
    enabled: true
    config:
      standard: youless-logger/vendor/roeldev/phpcs-ruleset/phpcs-ruleset.xml

  phpmd:
    enabled: true
    config:
      file_extensions: "php"

  shellcheck:
    enabled: true
