version: '3.4'

services:
  travis:
    image: roeldev/casa-youless-logger:${IMAGE_TAG}
    build:
      context: .
      args:
        - VERSION=:${IMAGE_TAG}

  local:
    image: roeldev/casa-youless-logger:local
    container_name: casa-youless-logger
    build:
      context: .
    ports:
      - 9080:80
    volumes:
      - ./.docker-volumes/config:/config/
      - ./.docker-volumes/data:/app/data/
      - ./.docker-volumes/log:/app/log/

  dev:
    image: roeldev/casa-youless-logger:dev
    container_name: casa-youless-logger_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PGID=100
      - PUID=1000
      - CRON_LOG_LEVEL=8
      - CRON_LOG_FILE=/dev/stdout
    ports:
      - 9081:80
    volumes:
      - ./app:/app/
      - ./.docker-volumes/config:/config/
      - ./.docker-volumes/data:/app/data/
      - ./.docker-volumes/log:/app/log/
      - ./.docker-volumes/composer:/composer/cache/
#      - ../../stellar-php/stellar:/app/vendor/stellar/stellar/
