version: '3'

services:
  prod:
    image: roeldev/casa-youless-logger:local-prod
    container_name: casa-youless-logger_prod
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .docker.env
    volumes:
      - ./project/config:/yl/config/
      - ./project/data:/yl/data/
      - ./project/log:/yl/log/

  dev:
    image: roeldev/casa-youless-logger:local-dev
    container_name: casa-youless-logger_dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        PRODUCTION_IMAGE: roeldev/casa-youless-logger:local-prod
    env_file:
      - .docker.env
    volumes:
      - ./project:/yl/
      - ./project/config:/yl/config/
      - ./project/data:/yl/data/
      - ./project/log:/yl/log/
      - ./.composer-cache:/root/.composer/
      - ../../stellar-php/stellar:/yl/vendor/stellar/stellar/
