version: '3.4'

services:
  casa-youless:
    build:
      context: .
      target: base
    image: roeldev/casa-youless
    container_name: casa-youless
    volumes:
      - youless/data:/youless/data
      - youless/log:/youless/log
    environment:
      - YOULES_PASSWORD=secret
      - DB_USERNAME=youless
      - DB_PASSWORD=secret
