version: '3.4'

services:
  travis:
    image: roeldev/casa-youless-logger:${IMAGE_TAG}
    build:
      context: .
      dockerfile: Dockerfile

  local:
    image: roeldev/casa-youless-logger:local
    container_name: casa-youless-logger
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    ports:
      - "9080:80"
    volumes:
      - ./.docker-volumes/config:/app/config/
      - ./.docker-volumes/data:/app/data/
      - ./.docker-volumes/log:/app/log/

  dev:
    image: roeldev/casa-youless-logger:dev
    container_name: casa-youless-logger_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        BASE_IMAGE: roeldev/casa-youless-logger:local
    env_file:
      - .docker.env
    ports:
      - "9081:80"
    volumes:
      - ./app:/app/
      - ./.docker-volumes/config:/app/config/
      - ./.docker-volumes/data:/app/data/
      - ./.docker-volumes/log:/app/log/
      - ./.docker-volumes/composer:/root/.composer/
#      - ../../stellar-php/stellar:/app/vendor/stellar/stellar/
