version: '3'

services:
  prod:
    image: roeldev/casa-youless-logger:local-prod
    container_name: casa-youless-logger_prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    volumes:
      - ./app/config:/app/config/
      - ./app/data:/app/data/
      - ./app/log:/app/log/

  dev:
    image: roeldev/casa-youless-logger:local-dev
    container_name: casa-youless-logger_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PRODUCTION_IMAGE: roeldev/casa-youless-logger:local-prod
    env_file:
      - .docker.env
    volumes:
      - ./app:/app/
      - ./app/config:/app/config/
      - ./app/data:/app/data/
      - ./app/log:/app/log/
      - ./.composer-cache:/root/.composer/
      - ../../stellar-php/stellar:/app/vendor/stellar/stellar/
